### PR TITLE
Other/add server templates

### PR DESCRIPTION
**Pull request by epacke**
Suggesting "other" instead of "docs" as the docs are hosted on the Wordpress server.

* Removed the make release package script
* Moved some folders I saw fitting (please give feedback if it did not make sense)
* Deleted old releases
* Added the Brotli iRule
 
The BFG tool to clean old files was java based and I could not bother installing it on my Mac. The git folder seems to be 25MB anyway so it's not a big problem I reckon.

### CODE REVIEW

**Comment by timriker** [comment]
BFG wants the current HEAD to not include any files we want to purge. I'll try it after we clean those release files out. I see 131M in my .git/ folder. I'll do some testing...

**Comment by timriker** [comment]
After a:
git gc --aggressive --prune=now
I'm down to:
$ du -sh .git
22M     .git

**Comment by epacke** [comment]
Nice! Let's merge?

**Review by timriker — APPROVED** [review]
looks good

**Pull request merged**
