### PR TITLE
Adding support for environment variables

### PR DESCRIPTION
**Pull request by epacke**
Closing #49

### CODE REVIEW

**Comment by timriker** [comment]
It looks like if the config has a username/password and one is also present in the env, that the config file takes priority. I would suggest that the env, if present, should take priority.

**Comment by epacke** [comment]
Good point. Initially I did not want to change the logic too much but what you said makes sense.

**Comment by timriker** [comment]
If the env vars are present, you could just push them into the in-memory config in the right places?

**Comment by epacke** [comment]
Re-wrote it like that. Also changed the order in the config validation... Not sure why, but it felt better.

**Comment by epacke** [comment]
> 
> 
> If the env vars are present, you could just push them into the in-memory config in the right places?

Agreed. But I would like to get rid of the global variables. How about doing that later?

**Comment by timriker** [comment]
What's this part for?

`log error "Malformed NAT file content detected: Check $_"($null -eq $SupportCheckOption.Username -or $SupportCheckOption.Username -eq "" -or $null -eq $SupportCheckOption.Password -or $SupportCheckOption.Password -eq "")`

**Comment by Patrik-Netent** [comment]
Let's call it paste la surprise. Nice catch.

**Comment by epacke** [comment]
Let's call it paste la surprise. Nice catch.

**Comment by timriker** [comment]
"credetnials"

$User in one place and $Username in the other?

**Comment by epacke** [comment]
I think Username makes more sense, but the change would require more testing. Voting for leaving as is.

**Review by timriker — APPROVED** [review]

**Pull request merged**
