### PR TITLE
Policy support

### PR DESCRIPTION
**Pull request by epacke**
This is Marius Bauers original PR. Going to fix the comments made by Tim and myself and eventually push it through.

* adding running version of policy collector as proposal for a new BigIP-Report feature. Only added some rare translations of the policy code into readable content.

Co-authored-by: Marius Bauer <mariusbauer@mariuss-mbp.speedport.ip>

### CODE REVIEW

**Comment by timriker** [comment]
probably want a new icon for the tab. Looks like it's using the same as Preferences at the moment.

**Comment by epacke** [comment]
> probably want a new icon for the tab. Looks like it's using the same as Preferences at the moment.

Agreed

**Comment by timriker** [comment]
Working against all my servers. Sorting by "Associated Virtual Servers" works. Data looks good. Useful to have there.

**Comment by epacke** [comment]
I can't seem to find the icon pack I used. Do you remember by any chance?

**Comment by epacke** [comment]
Maybe this one actually:
https://www.elegantthemes.com/blog/freebie-of-the-week/beautiful-flat-icons-for-free

**Comment by timriker** [comment]
nope. I've used Font Awesome for glyphs before. That would be a larger change though.

**Comment by timriker** [comment]
probably should change the other "policy" referenced to "polices". Working on it...

**Comment by timriker** [comment]
can we make f5 edit links for policies?

**Comment by epacke** [comment]
> can we make f5 edit links for policies?

Not sure tbh. You have to create a draft to get to edit mode but you might be able to view it via a link. I'm willing for forego the edit links and just push this through now. Unless you feel the need to add them?

**Review by timriker — APPROVED** [review]
Looks great to me. We can edit edit links later if/when we figure it out. :)

**Pull request merged**
