### PR TITLE
#141 Adding support for address (Closes #31) and port lists (Closes #69 #141), discard token (Closes #143)

### LINKED ISSUE #31: handle shared object address pools
VSs can be created with multiple addresses from a shared address pool.

We should probably poll the shared objects, store them, and link to the pool from the ip:port field in a virtual server.

### LINKED ISSUE #69: Port list support
[BenT](https://devcentral.f5.com/s/profile/0051T000008cfiWQAQ) on Devcentral requested support for port lists.

Not sure how to visualize this but maybe a modal could do it?

Ben was kind enough to provide a sample configuration:

```
net port-list /Common/web_443-8443-8080_ports {
    description web_443-8443-8080_ports
    ports {
        443 { }
        8080 { }
        8443 { }
    }
}
ltm pool /Common/pool_vip_portlist_example {
    load-balancing-mode least-connections-node
    members {
        /Common/172.1.2.5:0 {
            address 172.1.2.5
        }
        /Common/172.1.2.6:0 {
            address 172.1.2.6
        }
    }
    monitor /Common/https_basic_443
}
ltm traffic-matching-criteria /Common/vip_portlist_example_VS_TMC_OBJ {
    destination-address-inline 1.2.3.4
    destination-port-list /Common/web_443-8443-8080_ports
    protocol tcp
    source-address-inline 0.0.0.0
}
ltm virtual /Common/vip_portlist_example {
    ip-protocol tcp
    pool /Common/pool_vip_portlist_example
    profiles {
        /Common/fastL4 { }
    }
    serverssl-use-sni disabled
    source-address-translation {
        type automap
    }
    traffic-matching-criteria /Common/vip_portlist_example_VS_TMC_OBJ
    translate-address enabled
    translate-port enabled
    vlans {
        /Common/proxy-vlan
    }
    vlans-enabled
}```

### LINKED ISSUE #141: Cannot convert value "any6" to type "System.Net.IPAddress". Error: "An invalid IP address was specified."
**Describe the bug**
If a VIP is configured with a port-list, BigIPreport stops running

**To Reproduce**
Configure a VIP with a port-list
port-list

**Config**
_tmsh list ltm virtual /Common/VIP_

ltm virtual VIP-int-sko-multi-vip {
    creation-time 2021-05-26:12:40:14
    ip-protocol tcp
    last-modified-time 2021-08-26:11:38:10
    persist {
        source_addr {
            default yes
        }
    }
    pool VIP-sko-multi-pool
    profiles {
        f5-tcp-lan { }
    }
    serverssl-use-sni disabled
    source-address-translation {
        pool VIP-int-sko-snatpool
        type snat
    }
    traffic-matching-criteria VIP-int-sko-multi-vip_VS_TMC_OBJ
    translate-address enabled
    translate-port enabled
    vs-index 5
}

_list security firewall port-list VIP-int-sko-multi-vip-ports_
security firewall port-list VIP-int-sko-multi-vip-ports {
    ports {
        50006 { }
        60006 { }
    }
}

**Error message**
Unable to cache virtual servers: Cannot convert value "any6" to type "System.Net.IPAddress". Error: "An invalid IP address was specified." (line 1038)

**Additional context**
BigIPReport version 5.6.2

### LINKED ISSUE #143: delete tokens before exit
Each user can have 100 tokens. We create one on each run and don't delete it. This means eventually I run out of tokens when testing.

This should not affect normal users, but we should clean up after ourselves.

### PR DESCRIPTION
**Pull request by epacke**
Potentially closes #141 

Needs testing though. Free @timriker ?

### CODE REVIEW

**Comment by timriker** [comment]
I still get an error if I use port lists:

Unable to cache virtual servers: The property 'length' cannot be found on this object. Verify that the property exists. (line 1736)

looking into it.

As part of our ipv6 migration, I presume we'll be using address lists too, which I don't think the report handles either.

**Review by timriker — APPROVED** [review]
added the code to handle and empty list, and it seems to work, so approving.

**Review by timriker — APPROVED** [review]
looks good to me. Can you squash and merge?

**Review by timriker — DISMISSED** [review]
checking the files as viewed again to see if that makes a difference.

**Comment by epacke** [comment]
I'll give it a go tonight 👍🏻

**Review by timriker — APPROVED** [review]

**Pull request merged**
