### PR TITLE
Click to copy monitor send strings

### LINKED ISSUE #89: Change the hover and copy to click to copy
The hover to copy is pretty ugly. Since Javascript has a well supported clipboard functionality we should change this to click to copy instead. Easy ticket if someone wants to get their hands dirty.

### PR DESCRIPTION
**Pull request by epacke**
This took longer than I intended. Started with this a while ago and then broke my wrist. Finished it using my left hand and it took ages... 🤣 

* Added unit tests
* Added click to copy
* Refactored the monitor send string functions
* Added Webpack to:
  - Allow browser friendly module handling while unit tests are still working
  - Bundling all our code into one bundle instead of multiple files

Fixes #89

### CODE REVIEW

**Comment by timriker** [comment]
The curl test does not seem to copy the send values. Perhaps we could improve that? I have a monitor that does:

GET /health HTTP/1.1\r\nHost:\r\nConnection: close\r\n\r\n

(complete with broken Host: header...)

and I get /health on the http link, but for curl I get:

curl -H "Connection:close" http://1.2.3.4:80/health

which does not include the Host: header. Not a big deal. I used to be able to click on the HTTP or curl links and test right in the browser. It seems you removed that? Perhaps we could make the "Member IP" an href to target=_blank so people can click there?

**Comment by timriker** [comment]
Can we bundle the other js files in with the webpack so there is only one to load? These should get cached, so probably not a big deal, but it might be nice for initial load times.

**Comment by epacke** [comment]
Good idea. I'll check the curl feedback.

**Comment by epacke** [comment]
> Can we bundle the other js files in with the webpack so there is only one to load? These should get cached, so probably not a big deal, but it might be nice for initial load times.

We might. Need to see if external files can be added.

**Comment by epacke** [comment]
Did a quick search as to the bundling of the JS files. Needs a third party plugin. If it's all the same to you I'm ok with skipping it.

**Review by timriker — APPROVED** [review]
Looking good. Merge away.

**Review by timriker — DISMISSED** [review]
I added crlf changes. Looks good to me.

**Comment by timriker** [comment]
The curl and http links probably need square brackets around the addresses. The nc link works fine.

**Comment by epacke** [comment]
> The curl and http links for IPv6 hosts probably need square brackets around the addresses. The nc link works fine.

You mean like this for curl links?
```
curl -H "Host:host.domain.com" -H "Connection:Close" "https://2001:0db8:85a3:0000:0000:8a2e:0370:7334:443/"
```

Not sure what you mean with quoting the http links?

**Comment by timriker** [comment]
This works:
curl -skv https://[2607:f8b0:400a:80b::200e]:443
These do not:
curl -skv https://2607:f8b0:400a:80b::200e:443
curl -skv https://2607:f8b0:400a:80b::200e.443

**Comment by epacke** [comment]
I think my latest commit takes care of that.

**Comment by epacke** [comment]
I need a new approval because of the new commits. :)

**Review by timriker — APPROVED** [review]
Looks great!

**Pull request merged**
