### PR TITLE
Feature/handle failed devices

### LINKED ISSUE #55: Configuration validation - Validation of paths not working
When testing for missing properties in the config file we test like so:
```
$null -eq <path>
```

This does not seem to work on newer versions of PowerShell. If it ever worked.

### PR DESCRIPTION
**Pull request by epacke**
Fixes #55
Adds #29 #61

### CODE REVIEW

**Comment by timriker** [comment]
Your commit moved config under config/ again. I'd prefer not to.

**Comment by epacke** [comment]
> 
> 
> if ($Global:bigipreportconfig.Settings.ReportRoot -eq "/"){ ? shouldn't that be "" ?

No, "" becomes "/". I did it that way to save writing one more conditional.

**Comment by timriker** [comment]
We should probably log each lb we reuse old data for. looks like we log failures to use cached data.

**Comment by timriker** [comment]
Fine with me if we change paths and out to use the same keys.

**Comment by epacke** [comment]
> 
> 
> Fine with me if we change paths and out to use the same keys.

Thinking to not do this in this PR. After this I need time to test the release without adding stuff. I only have a week left with a bigger F5 environment.

**Comment by timriker** [comment]
could have an optional env var for config name. then you won't have to change the config path for testing.

**Comment by timriker** [comment]
Do we need all three? FailedDevice FailedDevices and MIssingData?

**Comment by epacke** [comment]
> 
> 
> Do we need all three? FailedDevice FailedDevices and MIssingData?

I tried not to touch the old logic too much as I did not want to introduce bugs.

**Comment by epacke** [comment]
After this excersise I really really miss typed languages. Sending these anonymous objects here and there is really horrible.

**Comment by timriker** [comment]
Do slack alerts change with Failed device if we got the old data?

**Comment by epacke** [comment]
> 
> 
> Do slack alerts change with Failed device if we got the old data?

```
# Clear old alerts for successful load balancers
        if ($Device.success){
            if($HasExistingAlert){
                log verbose "Clearing failed device alert for $DeviceName"
                $FailedDeviceAlerts.Remove($DeviceName)
            }
            Continue
        }
```

If an alert exists for a device with successful indexing the alert will be removed from state.

**Comment by timriker** [comment]
I meant if a device fails this run, but we have old data, do we alert? and does the alert say we have old data?
We're not using slack, so I'm just curious.

**Comment by epacke** [comment]
> 
> 
> I meant if a device fails this run, but we have old data, do we alert? and does the alert say we have old data?
> We're not using slack, so I'm just curious.

The device shows up with a red tint in the device table
It will alert after the configured X failures has occurred and supress alerts for a duration of a configured Y hours

**Comment by epacke** [comment]
> 
> 
> I meant if a device fails this run, but we have old data, do we alert? and does the alert say we have old data?
> We're not using slack, so I'm just curious.

The logic should make it easy to add a teams hook, if you can stomach microsofts json format...

**Comment by Patrik-Netent** [comment]
> 2021-04-30 13:25:22 Missing options in the Supportcheck config. Update the the latest version of the file and try again.
> 
> Not sure what I'm missing. I don't see a "SupportCheckOption"

Wonder why I did not run into that one

**Comment by epacke** [comment]
> 
> 
> 2021-04-30 13:25:22 Missing options in the Supportcheck config. Update the the latest version of the file and try again.
> 
> Not sure what I'm missing. I don't see a "SupportCheckOption"

Wonder why I did not run into that one.

**Comment by epacke** [comment]
Fixed (I think). Try again?

**Comment by timriker** [comment]
2021-04-30 13:32:52 Logging has been enabled but all logging fields has not been configured

**Comment by timriker** [comment]
/Settigs/LogSettings/LogLevel typo

**Comment by epacke** [comment]
> 
> 
> /Settigs/LogSettings/LogLevel typo
Did not run into that one either. Not even with a fresh shell.

**Comment by epacke** [comment]
Fixed

**Comment by timriker** [comment]
Line |
2309 |  $Global:State["failedDevices"] = Get-FailedDeviceAlerts -Devices $Rep …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'FailedDevices' cannot be found on this object. Verify that the property exists.

**Comment by Patrik-Netent** [comment]
> Line |
> 2309 | $Global:State["failedDevices"] = Get-FailedDeviceAlerts -Devices $Rep …
> | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> | The property 'FailedDevices' cannot be found on this object. Verify that the property exists.

Did you update the config file? :D

**Comment by timriker** [comment]
> Did you update the config file? :D

No, but I didn't get a config file failure message either.

**Comment by epacke** [comment]
Will fix that

**Comment by epacke** [comment]
Fixed I think. Will need to do the same for the other ones but test again for now?

**Comment by timriker** [comment]
I copied the example section over. Still getting:
2021-04-30 13:42:31 Missing Failed devices config, please update to the latest configuration file

**Comment by timriker** [comment]
Config error messages should really contain the _exact_ tag missing from the config.

**Comment by timriker** [comment]
ah. missed a copy. trying again...

**Comment by timriker** [comment]
"devices that was not" => "devices that were not"

**Review by timriker — APPROVED** [review]

**Comment by epacke** [comment]
Thanks Tim. Let's hope for a stable week of testing. :)

**Pull request merged**
