### PR TITLE
Hash rework #36

### PR DESCRIPTION
**Pull request by timriker**
column searches fill in from column().search() on draw().
url can reference virtualserver or pool searches. Only the active view will have it's search applied.
example pool search:
#m=p&q=pool_&0=-
virtualserver search:
#m=v&q=-psb&0=-&1=vs_
shadow layers remain the same.
#m=v&q=-psb&0=-&1=vs_&virtualserver=/Common/vs_example_HTTPS@lb-example&irule=/Common/sb/Rule_http_log@lb-example

### CODE REVIEW

**Comment by epacke** [comment]
Hey Tim
Sorry for the delay in my review! The code looks good except for some linting issues. Do you want help with the cypress tests?

**Comment by timriker** [comment]
Sure. I've upgraded my WSL distro to Ubuntu 22.04 so hopefully the tools are more up to date.

**Comment by epacke** [comment]
Figured I'd give you a hand with the Cypress tests. I've updated them now but there's one issue that I think I've found:

To reproduce:

1. Load up bigipreport
2. Make a column search, ie: `https://localhost:8443/#m=v&v,3=192.1`
3. Close the tab
4. Paste `https://localhost:8443/#m=v&v,3=192.1` in the location bar
5. The page now renders like it should, but the column search is not added and the results is not highlighted

Compare this:
image

To this:
image

If this is fixed I believe the tests will pass. If not I'll have another go at them.

**Comment by timriker** [comment]
hashes should be working now. search fields should populate, and highlighting should work.

There is still an issue with fields that contain invalid url characters, or comma. I need to do some escaping and unescaping.

**Comment by timriker** [comment]
also:
https://github.com/CodeByZach/pace/issues/470
https://github.com/PowerShell/PowerShell/issues/18510

**Comment by timriker** [comment]
Now with uri encode/decode which should handle fields with regex, comma, etc.

**Review by epacke — APPROVED** [review]
Real darn good work Tim. You're truly a superstar!

**Pull request merged**
