### PR TITLE
Feature/slack alerts (Closes #48, #58, #59)

### LINKED ISSUE #48: Slack webhook support
## Short
Having Slack webhook support would be a much more modern approach than email.
Suggestion is to save potential alerts in a json file, just like the support state. 

In the case of certificate expiration we could let the user alert toggle alerts on/off per type and configure how many alerts per type+key the report should send (*X hours/days/minutes* per *alertKey*).

The state could be saved in `/json/alerts.json` and we could clean the file from events older than X amount of days at each run.

## Example configuration

```xml

<!--
    The webhook to use when sending Slack alerts
-->

<SlackWebhook>https://slack.webhook.url</SlackWebHook>

<!--
    certificateExpiration
    Description: Have BigIPReport alert when certificates are about to expire
    WaitHoursBetween: How many hours between alerting, per certificate

    dataCollectionError
    Description: Have BigIPReport alert when there is issues connecting to a device
    WaitHoursBetween: How many hours between alerting, per device 
-->

<SlackAlerts>
    <certificateExpiration>
        <Enabled>True</Enabled>
        <WaitHoursBetween>24</WaitHoursBetween>
    </certificateExpiration>
    <dataCollectorError>
        <Enabled>True</Enabled>
        <WaitHoursBetween>4</WaitHoursBetween>
    </dataCollectorError>
</SlackAlerts
```

## Example json data

```json
[
  {
      "type": "certificateExpiration",
      "alertKey": "/Common/my-cert.com",
      "message": "The certificate /Common/my-cert.com is about to expire.",
      "lastAlerted": "1618832177"
  }, {
    "type": "dataCollectorError",
    "alertKey": "myltm.example.com",
    "message": "Failed to get a token from XXXX.",
    "lastAlerted": "1618832177"
  }
]
```

What do you think?

### PR DESCRIPTION
**Pull request by timriker**
#48 #58 #59

### CODE REVIEW

**Comment by timriker** [comment]
I don't want the config in config/

In fact, I'd rather have it named bigipreport.xml (or .yaml if we change it)

**Comment by timriker** [comment]
I'd rather have modules/ or similar over data-collector-modules/

As I've commented on the other branch, I'm concerned with the change in pwd and with the duplicated code in the current "modular" design.

**Comment by timriker** [comment]
I don't think a modules/module-name/module-name.ps1 is required. modulename/module.ps1 should suffice.

**Comment by epacke** [comment]
> 
> 
> I don't want the config in config/
> 
> In fact, I'd rather have it named bigipreport.xml (or .yaml if we change it)

I agree with you. This is still a draft PR and I put it there to be able to run code in both K8s and command line without messing around with parameters. Will change back later.

**Comment by epacke** [comment]
> 
> 
> I'd rather have modules/ or similar over data-collector-modules/
> 
> As I've commented on the other branch, I'm concerned with the change in pwd and with the duplicated code in the current "modular" design.

If I understand correctly the pwd will not be changed when including files with the "dot" notation. As far as the "modules" concerns they are all in the top directory. Powershell really sucks for this purpose...

**Comment by epacke** [comment]
> 
> 
> I don't think a modules/module-name/module-name.ps1 is required. modulename/module.ps1 should suffice.

Let's discuss this in the chat? Hit me up early morning your time? I am also not really fond of the directory name. Ideally it should be clear that it's modules for the powershell script.

**Comment by timriker** [comment]
Hmm. Looks like since I added the last commit, I can no longer "review" the PR. 🤣
I approve of this PR. Let's merge it.

**Review by epacke — APPROVED** [review]

**Pull request merged**
