### PR TITLE
Only run the support checks once per day

### PR DESCRIPTION
**Pull request by epacke**

### CODE REVIEW

**Comment by epacke** [comment]
Maybe it'd make more sense to maintain this as a separate json file and stitch it together when rendering?

**Comment by timriker** [comment]
each thread claims to create a statefile:
2021-04-12 16:23:35 State file did not exist, creating a new one
2021-04-12 16:23:39 lb-psb-a...:State file did not exist, creating a new one
2021-04-12 16:23:39 lb-psb-b...:State file did not exist, creating a new one
2021-04-12 16:23:39 lb-rsb-a...:State file did not exist, creating a new one

**Comment by timriker** [comment]
state file is created even if supportcheck is disabled.

**Comment by timriker** [comment]
The datestamp on the statefile should suffice for the time check. no need to store one.
I don't see any load balancer state stored in my state file.
It looks like you are loading the state from the previous report? I run with different xml files frequently, so json/loadbalancers.json might well have different loadbalancers in it than the current xml file.
I'd recommend removing the datestamp from state.json. and using the filedate.
I'd recommend storing the license state for loadbalancers in the -state.json and using that info if it's less than 24 hours.
I'd consider making the 24 hours configurable in the config xml file.

**Comment by Patrik-Netent** [comment]
> state file is created even if supportcheck is disabled.
> 
> The file check AND the file creation should be contingent on the xml having checking enabled.

The idea with the state file was to carry some form of state between executions so even if you disable the support state checks it should still create it.

> each thread claims to create a statefile:
> 2021-04-12 16:23:35 State file did not exist, creating a new one
> 2021-04-12 16:23:39 lb-psb-a...:State file did not exist, creating a new one
> 2021-04-12 16:23:39 lb-psb-b...:State file did not exist, creating a new one
> 2021-04-12 16:23:39 lb-rsb-a...:State file did not exist, creating a new one
> 
> easiest fix would be to move this code after the forks, so it only executes once.

Agreed. And it should only create it once as it does not _really_ create the file at that point, only initites the variable that contains the state. Either way, I got this jobs thing way wrong and need to fiddle around a bit.

I think we probably should refactor this giant ps1 file and split it up into more pieces. What do you think? One idea is to move the code that runs in the job to a single file. Then we could include the helper functions by calling `. .\function.ps1`.


> The datestamp on the statefile should suffice for the time check. no need to store one.
Agreed! There are other things we could use this state file for though such as throttling Slack alerts, mail alerts etc.

> I don't see any load balancer state stored in my state file.
Strange. My state file looks like this:

```
{
  "LastSupportCheck": 1618296352.0
}
```

> It looks like you are loading the state from the previous report? I run with different xml files frequently, so json/loadbalancers.json might well have different loadbalancers in it than the current xml file.

Yeah, the point was to run this once. 

> I'd recommend removing the datestamp from state.json. and using the filedate.
I think having some form of state could be useful. While we don't have to use it in this case I reckon we should find a way to include it?

> I'd recommend storing the license state for loadbalancers in the -state.json and using that info if it's less than 24 hours.
Good idea!

> I'd consider making the 24 hours configurable in the config xml file.
I'd wonder why anyone would want to do it more often, or less seldom than 24h? It's just one more thing to test when changing the script.

* Which state are you referring to? I get time stamps in mine.
The state contains a key with the timestamp. The idea was to only store data that needs to be persisted there. As a variable storage between script executions if you will.

**Comment by epacke** [comment]
> state file is created even if supportcheck is disabled.
> 
> The file check AND the file creation should be contingent on the xml having checking enabled.

The idea with the state file was to carry some form of state between executions so even if you disable the support state checks it should still create it.

> each thread claims to create a statefile:
> 2021-04-12 16:23:35 State file did not exist, creating a new one
> 2021-04-12 16:23:39 lb-psb-a...:State file did not exist, creating a new one
> 2021-04-12 16:23:39 lb-psb-b...:State file did not exist, creating a new one
> 2021-04-12 16:23:39 lb-rsb-a...:State file did not exist, creating a new one
> 
> easiest fix would be to move this code after the forks, so it only executes once.

Agreed. And it should only create it once as it does not _really_ create the file at that point, only initites the variable that contains the state. Either way, I got this jobs thing way wrong and need to fiddle around a bit.

I think we probably should refactor this giant ps1 file and split it up into more pieces. What do you think? One idea is to move the code that runs in the job to a single file. Then we could include the helper functions by calling `. .\function.ps1`.


> The datestamp on the statefile should suffice for the time check. no need to store one.
Agreed! There are other things we could use this state file for though such as throttling Slack alerts, mail alerts etc.

> I don't see any load balancer state stored in my state file.
Strange. My state file looks like this:

```
{
  "LastSupportCheck": 1618296352.0
}
```

> It looks like you are loading the state from the previous report? I run with different xml files frequently, so json/loadbalancers.json might well have different loadbalancers in it than the current xml file.

Yeah, the point was to run this once. 

> I'd recommend removing the datestamp from state.json. and using the filedate.
I think having some form of state could be useful. While we don't have to use it in this case I reckon we should find a way to include it?

> I'd recommend storing the license state for loadbalancers in the -state.json and using that info if it's less than 24 hours.
Good idea!

> I'd consider making the 24 hours configurable in the config xml file.
I'd wonder why anyone would want to do it more often, or less seldom than 24h? It's just one more thing to test when changing the script.

* Which state are you referring to? I get time stamps in mine.
The state contains a key with the timestamp. The idea was to only store data that needs to be persisted there. As a variable storage between script executions if you will.

**Comment by epacke** [comment]
Realized that the way these global variables is used makes it very hard to break out some of this functionality. There's so much I'd like to change with this script. First being the language... :D

**Comment by epacke** [comment]
Maybe put these the statefile in the json folder even though it's not used in the js-app? Lunch is over, will tinker more tonight.

**Comment by timriker** [comment]
I often run different xml files in the same directory for different sets of F5s while testing. I set the ReportRoot to "underlay" so that js, css, and image changes take effect without re-running a report.
Storing the support state under ReportRoot means that it might not match the different report xml files.
Storing the state in a name derived from the xml file would keep a different state for each xml I have. I like that.
Loading and re-storing each LB support state in a combined file under ReportRoot would be a more complicated, but more complete solution.
ie: a.xml has lb-foo-a, lb-foo-b, and lb-bar-a in it. b.xml has lb-baz-a and lb-baz-b, and all.xml has them all. Where do we store the state such that running a.xml or b.xml does not wipe out state from the other xml? and where all.xml can find it?`

**Comment by timriker** [comment]
Re-writing the report in Python or something would be great, but very time consuming. I'd start running a new report in parallel if you want to commit that kind of time. It would be a big project.

**Comment by Patrik-Netent** [comment]
> Re-writing the report in Python or something would be great, but very time consuming. I'd start running a new report in parallel if you want to commit that kind of time. It would be a big project.

Probably not going to happen, but it'd be nice. If I did it I'd probably vote for Nodejs + Typescript. Concurrency in javascript is built in and easy to use.

**Comment by timriker** [comment]
Currently $PollLoadBalancer is used to find which load balancer a polling thread should use.
We could add to the list and make it a more generic thread name. Ie:
```
if ($PollLoadBalancer -eq "supportstatus") {
 do support status work
 return support status in json
 exit
}
```
Then if Support status is enabled, we add "supportstatus" to the $DevicesToStart even though it's not a device. We could rename DevicesToStart to JobsToStart and PollLoadBalancer to JobName or something like that.

This would mean that we can just test the supportstatus with:
`./bigipreport config.xml supportstatus`
and that normally this polling would run in parallel with the other lb polling.

**Pull request merged**
