### PR TITLE
Feature/refactor powershell

### PR DESCRIPTION
**Pull request by epacke**

### CODE REVIEW

**Comment by timriker** [comment]
Putting the modules in a different directory results in the config file being looked for in that directory if we try testing just the module. ie:

pwsh data-collector-modules/Get-LTMInformation.ps1 some.xml lb.example.com

The module will fail to find some.xml as it starts in data-collector-modules/

putting the modules in the current directory is also less than ideal.

The duplicate code in the modules from the main script is also less than ideal.

Overall, so far, I'm not seeing this as a will. We're trading one complication for another complication.

**Comment by epacke** [comment]
This command runs just like it should:
`C:\Users\user\Documents\BigIPReport> .\data-collector-modules\Get-LTMInformation.ps1 .\bigipreportconfig.xml bigip-01.xip.se location`

So does this one:
`PS C:\Users\user\Documents\BigIPReport> .\bigipreport.ps1`

Running **without** location does not work though, but I don't see an issue with that. Do you?

Benefit of splitting this as I see it is that the code base will be easier to follow. Main script starts jobs of the data-collector and should we want to add ie. supports check as a job we can do that too. This recursive method that we're using right now is a bit obtuse imho.

**Comment by epacke** [comment]
> The duplicate code in the modules from the main script is also less than ideal.

The PR is not fully done. I think we might have to live with _some_ duplication, but if you see something that can be removed, feel free to update.

**Comment by timriker** [comment]
I've not tried pwsh 6/7 on win/lin to see how pwd is handled. adding "location" overrides whatever default pwd powershell might think you have. This is complicated by .NET code having yet another current working directory, so calls that are .NET implementations might think the pwd is different than the powershell native commands think. Ugh..
When's the node.js rewrite going to be ready? 🤣

**Comment by epacke** [comment]
> I've not tried pwsh 6/7 on win/lin to see how pwd is handled. adding "location" overrides whatever default pwd powershell might think you have. This is complicated by .NET code having yet another current working directory, so calls that are .NET implementations might think the pwd is different than the powershell native commands think. Ugh..

Super icky, I know, but I'd rather take this than the recursive calls. Pest or Colera... 

> When's the node.js rewrite going to be ready? 🤣

Haha, give it another 2 years! :D

**Pull request closed without merging**
