### PR TITLE
Adding enabled and availability as column headers in the vs table

### PR DESCRIPTION
**Pull request by epacke**
#131

### CODE REVIEW

**Comment by epacke** [comment]
The e2e tests needs some love, but it's ready for testing.

**Comment by epacke** [comment]
Now it works. 👍

**Review by timriker — APPROVED** [review]

**Comment by timriker** [comment]
Are we going through with this? or should I look into adding the columns only on export?

**Comment by epacke** [comment]
I think columns only makes more sense to save screen real estate. Dismissing.

**Pull request closed without merging**
